name: Persist CSV database to Git commit
on:
  schedule:
    # At 5am every day
    - cron: 0 5 * * *
  workflow_dispatch:
jobs:
  persist-csv-database-to-git-commit:
    name: Persist CSV database to Git commit
    runs-on: ubuntu-latest
    permissions:
      # Write permissions for $GITHUB_TOKEN (to commit and push)
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '7'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm tsx scripts/updateCsvDatabaseRecords.ts data/persisted-to-git/database.csv
      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add data/persisted-to-git/database.csv
          git commit -m "Update CSV database with new records"
          git push
